import { ImageResponse } from "next/og";

// Branded 1200×630 card for link previews (Open Graph + Twitter). Generated by
// Next's file convention — no asset to maintain. Uses Satori's default font, so
// hierarchy comes from size/weight/color rather than custom typefaces.

export const alt = "Caseworker — your advocate for impossible paperwork";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#ffffff",
          padding: "76px 84px",
        }}
      >
        {/* brand */}
        <div style={{ display: "flex", alignItems: "center" }}>
          <div
            style={{
              width: 60,
              height: 60,
              borderRadius: 15,
              background: "#0e7c5a",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <svg width="36" height="36" viewBox="0 0 24 24" fill="none">
              <path
                d="M12 3v18M5 8h14M7 8l-3 6h6L7 8zm10 0l-3 6h6l-3-6z"
                stroke="#fff"
                strokeWidth="1.7"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <div style={{ marginLeft: 20, fontSize: 32, fontWeight: 600, color: "#14171c" }}>
            Caseworker
          </div>
        </div>

        {/* headline */}
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              fontSize: 78,
              fontWeight: 600,
              lineHeight: 1.05,
              letterSpacing: "-0.02em",
              color: "#14171c",
            }}
          >
            The letter that beats you,&nbsp;
            <span style={{ color: "#0a5e44" }}>beaten back.</span>
          </div>
          <div
            style={{
              display: "flex",
              marginTop: 30,
              fontSize: 31,
              lineHeight: 1.4,
              color: "#6c7480",
              maxWidth: 940,
            }}
          >
            Snap a photo of a denial, a benefits cut, or a surprise bill. Caseworker finds your
            rights and deadlines — and drafts the response that gets it reversed.
          </div>
        </div>

        {/* footer */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", fontSize: 26, fontWeight: 600, color: "#0a5e44" }}>
            caseworker-eta.vercel.app
          </div>
          <div style={{ display: "flex", fontSize: 21, color: "#9aa1ab" }}>
            Claude · ElevenLabs · MCP · Vercel
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}
